"""Added Admin to AccountType

Revision ID: 7579547b1dba
Revises: 8e4d4503bee4
Create Date: 2026-07-18 22:53:45.873134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7579547b1dba'
down_revision: Union[str, Sequence[str], None] = '8e4d4503bee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo_url')
    # ### end Alembic commands ###
